### ISSUE TITLE
[ios] textarea 键盘弹起时，如果调用页面滚动，fixed 定位的元素有概率被推走

### ISSUE THREAD

**Issue by xiaweiss** [xiaweiss/miniprogram-bug-report#121]
ios 默认输入法复现概率极低，百度输入法复现概率极高。

录屏：
第一次是正常弹起，第二次是弹起后被推走了

https://github.com/xiaweiss/miniprogram-bug-report/assets/17960084/d66c75f8-f36b-4654-b2df-8c271c2bc39c

**Comment by sdz123** [comment]
https://github.com/xiaweiss/miniprogram-bug-report/assets/19849443/cdc714e0-8032-4ff4-ae5a-ee1f002b79b4

有什么解决方案么，我这苹果原生输入法百分百复现

**Comment by xiaweiss** [comment]
@sdz123 可以看下「墨问」小程序的评论框，我目前使用的 fixed 也没有完全解决。百度输入法几乎百分百复现，其他输入法目前概率低。我考虑换成整个页面 scroll-view 的方式，来使用 absolute 布局试试。

目前使用 fixed 的话，可以在输入框区域盖上一个 `<view catch:tap="focus" />`，点击时，先使用  js 聚焦 => 增大底部占位高度 => 计算要滚动到哪里 => wx.pageScrollTo

**Comment by xiaweiss** [comment]
考虑更换布局方式，使用 scroll-view 的方式看看

**Comment by xiaweiss** [comment]
hack: 使用自定义导航栏 + scroll-view + absolute 定位的方式布局
