### ISSUE TITLE
scroll-view 默认打开 bounce，加载更多页时，滚动会回弹

### ISSUE THREAD

**Issue by xiaweiss** [xiaweiss/miniprogram-bug-report#13]
https://user-images.githubusercontent.com/17960084/231049623-9632a4df-bd4a-4146-b65b-50d8245202c6.MP4
        
如果关闭了 bounce，则会触发另一个问题 #2

**Comment by ele828** [comment]
这个问题已修复，安卓最新版应该就可以，iOS 跟在近期的版本上

**Comment by xiaweiss** [comment]
感谢
