### ISSUE TITLE
[skyline] textarea 不支持 auto-height，导致无法展示文字

### ISSUE THREAD

**Issue by xiaweiss** [xiaweiss/miniprogram-bug-report#143]
代码片段：https://developers.weixin.qq.com/s/OAmBrEmk7GN1

设置了 css 去覆盖默认的高度，不起作用。

![image](https://github.com/xiaweiss/miniprogram-bug-report/assets/17960084/20aab308-e15d-4226-aeb4-9fa5ff34f471)

**Comment by xiaweiss** [comment]
已修复，待发版

**Comment by seasonhuang** [comment]
3.1.3 已解决

**Comment by xiaweiss** [comment]
![image](https://github.com/xiaweiss/miniprogram-bug-report/assets/17960084/b8bdb5c8-c0e5-4d38-a2ae-e8aa845c9e91)

如图，现在基础库 3.1.4 了，ios 真机上高度依然过高 @seasonhuang

**Comment by xiaweiss** [comment]
基础库 3.3.2 已修复
