### ISSUE TITLE
[android] textarea 组件，使用 wx:if 切换后高度异常

### ISSUE THREAD

**Issue by xiaweiss** [xiaweiss/miniprogram-bug-report#173]
代码片段：https://developers.weixin.qq.com/s/D0exB3mg7fLh

代码片段 2 使用 view 的 hidden 属性，同样可以复现：https://developers.weixin.qq.com/s/CjyvxHmX7QGh

录屏：

https://github.com/xiaweiss/miniprogram-bug-report/assets/17960084/c70b3b08-3ef8-427c-ae4d-b5d2ff4ace15

**Comment by xiaweiss** [comment]
通过 class 设置样式 height: auto; 会好些，依然有小概率出错
代码片段：https://developers.weixin.qq.com/s/SChEp3mO7EL9

**Comment by xiaweiss** [comment]
等组件 ready 后再设置 auto-height: true，不会出错，但是会明显闪烁一下

**Comment by xiaweiss** [comment]
hack：先给外层设置样式 visibility: hidden; 隐藏，确保 auto-height 初始值是 false
延时或者自定义组件 ready 后，再设置 auto-height 为 true，并且移除样式 visibility: hidden;

**Comment by xiaweiss** [comment]
https://developers.weixin.qq.com/community/develop/doc/000240d8bb434012c040fc1b96bc00

**Comment by gaojunran** [comment]
基础库 3.15.3 修复，等发版时会再评论下，感谢 bug 复现！
