### ISSUE TITLE
[skyline ios] input focus 时被 wx:if 销毁后，上推的界面无法复原

### ISSUE THREAD

**Issue by xiaweiss** [xiaweiss/miniprogram-bug-report#201]
代码片段：https://developers.weixin.qq.com/s/kypbU0mH7rRR

安卓正常

https://github.com/xiaweiss/miniprogram-bug-report/assets/17960084/c4fd1600-8120-49c1-ad33-436697b1225d

**Comment by seasonhuang** [comment]
能否提供个代码片段

**Comment by xiaweiss** [comment]
@seasonhuang 代码片段：https://developers.weixin.qq.com/s/kypbU0mH7rRR
聚焦状态下，直接点击关闭按钮就可以复现。
