### ISSUE TITLE
[android] BackgroundAudioManager 背景音频，设置 src 时，多触发了一次 onTimeUpdate 值 0，导致进度条抖动

### ISSUE THREAD

**Issue by xiaweiss** [xiaweiss/miniprogram-bug-report#250]
复现步骤：
1. 设置 audio.src 音频1
2. 设置 audio.startTime
3. 设置 audio.src 音频2

设置音频 2 时，会多触发一次 audio.onTimeUpdate  0。导致进度条先回到 0 ，再回来正确进度，抖动一次

此问题 ios 正常。

https://github.com/xiaweiss/miniprogram-bug-report/assets/17960084/f8dfb238-85ac-4c79-93e5-85b3dc49cef6

**Comment by xiaweiss** [comment]
hack: 看下 duration 的值，如果为 0，则忽略本次事件
```javascript
audio.onTimeUpdate(() => {
  const { currentTime: current, duration } = audio
  if (duration === 0) return

  // ...
})
```

**Comment by gaojunran** [comment]
这个问题将在基础库后续版本修复。其余 #254 #251 #253 #100 相关问题后面会反馈给客户端同学修复
