### ISSUE TITLE
[skyline] 图文混排时，图片稍大时，会撑大行高

### ISSUE THREAD

**Issue by xiaweiss** [xiaweiss/miniprogram-bug-report#262]
代码片段：https://developers.weixin.qq.com/s/zTs2Nmmx76Sa

见下图：css 样式为文字 15px，行高 20px，图片 19px，实际上行高被撑大

当图片高度为 16px 时，行高才能保持正常

<img width="363" alt="image" src="https://github.com/xiaweiss/miniprogram-bug-report/assets/17960084/8b00ff3d-4f39-44e4-858c-fadfbcf01f20">

**Comment by TtTRz** [comment]
这里的原因是 skyline 目前在图文混排上只支持 inline-block，所以会导致 inline-block 的元素撑开行高。（这个表现是对齐 webview inline-block 的）
之后支持完整 inline 之后会比较好的对齐 webview 的表现。

**Comment by xiaweiss** [comment]
好的，谢谢
