### ISSUE TITLE
[全平台] textarea 文字较多时，auto-height 计算出的高度错误

### ISSUE THREAD

**Issue by xiaweiss** [xiaweiss/miniprogram-bug-report#269]
代码片段：https://developers.weixin.qq.com/s/UBDx5Hmm7sSd

mac、安卓表现为内部出现滚动条，预期无滚动条

ios 表现为文字无法展示，但插入新的行再删除时，隐约可见

ios 录屏：
https://github.com/user-attachments/assets/ee9a3ce3-c4a7-42a0-a39e-9aa880eff555

**Comment by xiaweiss** [comment]
hack: 不能设置 padding，而且 mac 需要把行高固定为 16.8px

hack2: 如果需要折叠，设置文字之前，先给 textarea 设置好 max-height

移动端代码片段：https://developers.weixin.qq.com/s/g7MLaHmd7fSa
mac 代码片段：https://developers.weixin.qq.com/s/SoMsXHm57gSN

**Comment by gaojunran** [comment]
基础库 v3.15.1 已修复，还没发

**Comment by gaojunran** [comment]
btw，可否留一个联系方式，后面会陆续追踪您提出的 issue 并修复，感谢您的反馈！ @xiaweiss

**Comment by xiaweiss** [comment]
感谢，我的微信：
<img width="200" height="200" alt="Image" src="https://github.com/user-attachments/assets/f772b5ce-ae08-40be-999a-5570f121d251" />

**Comment by xiaweiss** [comment]
基础库 3.15.1 已修复

但是 android 和 mac 在最后创建新行时，会有闪烁现象，这个旧基础库也有
