### ISSUE TITLE
textarea cursor-spacing 不生效和动态设置 adjust-position问题

### ISSUE THREAD

**Issue by mice33** [xiaweiss/miniprogram-bug-report#312]
https://developers.weixin.qq.com/community/develop/doc/000e423d4e40982115a28858961000

@xiaweiss 这个你有碰到过么

**Comment by xiaweiss** [comment]
> 原帖内容：
> 问题1. 当 textarea 设置 adjust-keyboard-to="bottom" 后 cursor-spacing 属性不生效
> 
> 问题2. 当 adjust-position 设置为 false, 再设置成 true 后, adjust-keyboard-to="bottom" 会失效, 变成 cursor 的效果如图所示
> 
> 代码片段 https://developers.weixin.qq.com/s/3gpYEHmD7bWJ 中包含了这两个情况的 textarea 可 100% 复现
> 
> 测试设备: iOS 18.2(22C152) / 微信版本 8.0.54 / 基础库版本 3.7.3 (2024.12.23 17:27:35)

不是 bug，是使用方式有误。

问题 1： adjust-keyboard-to="bottom" 对其的是输入框底部，与光标无关，cursor-spacing 预期就是不生效的
问题 2：adjust-position 是键盘推起方式，属于在使用之前就要「预设」的值，不建议动态修改。

**Comment by mice33** [comment]
但以上问题在安卓端都没复现, 都可正常按我预期展示.
adjust-position 我已经测出预设 false,再动态修改就没问题了.
但 cursor-spacing 在 iOS 端不生效这个不知道如何解决

**Comment by xiaweiss** [comment]
adjust-keyboard-to 不要设置，使用默认值 cursor，cursor-spacing 才能生效

**Comment by xiaweiss** [comment]
建议是 adjust-position 全程设置为 false，不要动态修改。cursor-spacing 其实也用不着。直接通过 wx.onKeyboardHeightChange 获取键盘高度来调整 textarea 的位置即可。

案例可以看「墨问便签」小程序的笔记评论效果
