### ISSUE TITLE
[skyline] 建议支持 textarea 的 placeholder-class 属性，一般 placeholder 颜色比实际输入的文本浅

### ISSUE THREAD

**Issue by xiaweiss** [xiaweiss/miniprogram-bug-report#46]
代码片段：https://developers.weixin.qq.com/s/zEVia0m37HJI

一般 placeholder 颜色比实际输入的文本浅

webview 模式是红色、skyline 模式失效了，是灰黑色

**Comment by xiaweiss** [comment]
目前未支持

**Comment by seasonhuang** [comment]
可以先使用 placeholder-style 替代？

**Comment by xiaweiss** [comment]
@seasonhuang 微信 iOS 版本 8.0.40，小程序基础库 3.0.0。测试了下 placeholder-style 一样无效的。

**Comment by seasonhuang** [comment]
@xiaweiss skyline 的 placeholder-style 需要传入一个对象，`{color: '#CC5656'}` ，iOS 版本 8.0.40 基础库 3.0.0 试了正常

**Comment by xiaweiss** [comment]
@seasonhuang 好的，谢谢反馈，这里语法变化了，需要写个判断条件
```javascript
placeholder-style="{{isSkyline ? {color: '#CC5656'} : 'color:#CC5656'}}"
```
代码片段：
https://developers.weixin.qq.com/s/mhIW78mJ7YKL
