### ISSUE TITLE
[开发者工具] skyline 文字被错误显示为斜体了

### ISSUE THREAD

**Issue by xiaweiss** [xiaweiss/miniprogram-bug-report#56]
代码片段：https://developers.weixin.qq.com/s/dkrYtqmp7IMa

<img width="404" alt="image" src="https://user-images.githubusercontent.com/17960084/236613741-947a503f-a98e-448d-93b6-a34f9c3274d3.png">

**Comment by seasonhuang** [comment]
macOS ARM64 Nightly 1.06.2310092 没有复现

**Comment by xiaweiss** [comment]
@seasonhuang 能复现，请看截图
<img width="1111" alt="image" src="https://github.com/xiaweiss/miniprogram-bug-report/assets/17960084/fced4e64-5a37-4d92-8ba7-b140c028fbc6">

**Comment by xiaweiss** [comment]
https://developers.weixin.qq.com/community/minihome/doc/0002268bb54c20c82c903337566800

**Comment by xiaweiss** [comment]
开发者工具 Nightly 1.06.2401122 已可以正常显示﻿
