### ISSUE TITLE
[skyline] <input type="nickname" /> 用户昵称组件，微信昵称没有完整显示

### ISSUE THREAD

**Issue by xiaweiss** [xiaweiss/miniprogram-bug-report#92]
微信昵称 xiawei，实际显示 xiawe，少显示了 i

![image](https://github.com/xiaweiss/miniprogram-bug-report/assets/17960084/7aed5503-de04-4b1e-9ee7-c14e3d674534)

**Comment by ManiaciaChao** [comment]
webview 下也是这个表现吗，这个浮窗的绘制逻辑是一样的

**Comment by xiaweiss** [comment]
@ManiaciaChao webview 下表现是正常的，可以完整显示昵称

**Comment by xiaweiss** [comment]
基础库 2.32.2 已修复
